apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: user
spec:
  group: cebpaas.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                userName:
                  type: string
                userPassword:
                  type: string
            status:
              type: object
              properties:
                state:
                  type: string
  names:
    kind: User
    plural: users
  scope: Namespaced
